apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDCDCCAfCgAwIBAgIUVJawer5IEY2Te+OY/p+n6cNzKnIwDQYJKoZIhvcNAQEL
    BQAwHDEaMBgGA1UEAxMRbXVsdGlwYXNzLXJvb3QtY2EwHhcNMjYwNzI5MTQwOTM2
    WhcNMjYxMDI3MTQwOTM2WjAcMRowGAYDVQQDExFtdWx0aXBhc3Mtcm9vdC1jYTCC
    ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMkyk508lPvHG2eDs8TRRWwa
    qJtTz3VlFG1iycUkwZgHeD1QJrDq8lqC2GEI4Cv7vn7UFHv3eP7yiP4KoZYOqEZx
    tkANLhm6ORk2se/gJyfmM3aiS+CyEZsYv4nGnftV/K0ngqL/FAWjB3enru3iBnLI
    ycDU2D3a5KSrvCU1y+EcG4/GB0TFpPT7VgSuBHCmBZV+lh5avIcp/HoC2c4uR2wQ
    qLC+fMmJHRrNN5ddnzuhIP9spn+nAH58im9Hz5Q38Y0ULOxjoqdIxaCsc/pbf2CK
    KFsg8iptx+3TeO/piL9eUZZ6kI2FHYkJLA5AjxlTw5GK1gD5gsnRUtxqS5MK6CEC
    AwEAAaNCMEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0O
    BBYEFH42Ejt+W051DU4SHuPbT0+iLhwfMA0GCSqGSIb3DQEBCwUAA4IBAQBdubAk
    YOXd/O9bo7mmnI73EUgtZfpcUzaPemX06etYUB1Q2HKtcYW7FnuTfZp8Ro9ITLxq
    DszqyxrCBZ3rCIt4zmUGEFtHsf1kpmcDqq4tubusj7DVkwlefKyRoTKwx2bKk579
    rOT4T3nRnfSe5vmbR7F4gLC71cz1VM2/vhCMXD6m7xbIrSvPeV4HXaYgN/4U75+G
    07P4DQj8pJOTk0deVLzoCLkdDrvVjete28GJBW4Dru9bb55aSl/VjciTJ7y9Vd/8
    pSSlHVjL4CwfwFqtL082YA+4nls+KRW0MJeCQ9NxPr4IWdkTdtJKz03JW/AwRBbB
    X83Ts7RKE3foMaX/
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: multipass-root-ca
  namespace: headlamp
