service:
  type: ClusterIP

config:
  inCluster: true

  oidc:
    externalSecret:
      enabled: true
      name: headlamp-oidc
      hasScopes: true

    callbackURL: https://headlamp.multipass.k3s/oidc-callback
    useCookie: true
