name: headlamp
namespace: headlamp
repoURL: https://kubernetes-sigs.github.io/headlamp/
chart: headlamp
targetRevision: 0.43.0
valuesFile: multipass/k3s/03-apps/applications/headlamp/values.yaml
expose:
  enabled: true
  host: headlamp.multipass.k3s
  tls: true
