alertmanager:
  enabled: false

pushgateway:
  enabled: false

server:
  retention: 3d
  persistentVolume:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

serverFiles:
  prometheus.yml:
    global:
      scrape_interval: 1m
      evaluation_interval: 1m

kube-state-metrics:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 96Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 10m
      memory: 16Mi
    limits:
      cpu: 100m
      memory: 48Mi