name: kube-prometheus-stack
namespace: monitoring

repoURL: https://prometheus-community.github.io/helm-charts
chart: kube-prometheus-stack
targetRevision: 86.0.0

valuesFile: multipass/k3s/03-apps/applications/kube-prometheus-stack/values.yaml
