name: podinfo
namespace: podinfo
repoURL: https://stefanprodan.github.io/podinfo
chart: podinfo
targetRevision: 6.15.0
valuesFile: multipass/k3s/03-apps/podinfo/values.yaml
kustomizePath: multipass/k3s/03-apps/podinfo
