apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: podinfo
  namespace: podinfo

spec:
  entryPoints:
    - websecure

  routes:
    - match: Host(`podinfo.multipass.k3s`)
      kind: Rule
      services:
        - name: podinfo
          port: 9898

  tls:
    secretName: podinfo-tls
