{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "grafana-oidc",
    "namespace": "monitoring"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "grafana-oidc",
        "namespace": "monitoring"
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "OIDC_CLIENT_ID": "AgB+PP4YG3wjj0EkcCXV2CM4xt3v/27svbsm8t8IPuSP1K//cNF4XBfBNmQ3v+qlMwDnrqsFB2hYLkS8MaM1zLaQqOlnfGgA6jADr6jjbyLBX+5L5eRnXdIsvMW5mU4tBJw+i9zL9pwT7r+pOxHoH4MS2eC6aGz1jc0AEwCUescgECFKrvJDsazEqmaOQq5bhvyqJSf3nr0gki2fbt8Tw2kjcn7q4PYc6IVZOS/tfirNpaqG1Uotcf6yvkvaxsN0tNfmQIrN27/AEsSWlyoG7dxZAM61d+cJcxCpAEVuwo9OAFBZhx9qOpf77rOPlneg6E/KJ0CbPI/WJ4RM1a+MSIFW+lVmm4E9jub6X93NROfeGOlLDr2afoPLRN4Wq2f+YUpJoczHhKi2ztJLNtxHKHJH5K9UVxGvCjnsueS4AXAHm7U7f3Ily1w12kgDlIC3rTLmIByEPlaBKIkHMbeqgJzjyMl2kfAKzNhWYyp57z1pKTdzcPU8p9knP1cwm8j4Gae1P7e047CKRkql81KhUcXLkbbTlM+XMRjj+X8ofxXJJuVWNoOjblz1uGZYGdQblK7NbbwJ3vuts09zvM/ZQGXzLzrbiFMFAhtuktL6klDi4Q3Y+r8J7EwdFbNiHt2hNxplsizgLv2FOe6OvaAtJbv6wcU2GPloU4Wco2BZS8rqqrXousp2NXZ/E6z5vHG/oUdKRVEKIMGA",
      "OIDC_CLIENT_SECRET": "AgCFa4/P7dzOpIhbE413eT4ZEo/Sgce1w/5I7P3ItjsZIhA0nfsd4DfQlzXzw92fiFL82J6b8hayOWH4wU4QnsuJA/7TuQ88R3HRt0cx/FuGKNTGcjelLJ/LmeOZ3Gr5s6BL0i3YVqyUS8NdVF4Wkg/+ZXriHBGwlwKa9+/Lflq268IuWTQYE02/2OwHeXajVm+0twS7IwPZFnktlXNs63T2PzfPJbNMvNapL75NZgE66AYeCTBwNzdmggTHkis19CymjoooCeIWFqEmiSjQvTa9M6gTVuOZ52hv7IizMqnyBKYbBRDntEdIp1+XIeh47sql7ICO+h3u9kk8wQIkEvEulOJYvntr7lHuJYBSCFxB8BpvHkYYbiNOGXn3n1u1kSRQiNuKBcnhph9Gi3dg3SNbwAqPrnAph8XxT0dM+Ih6kAZoYF+7B9L2PA2Jf6xaIZNy8MAgSAIvNsCyhjY7OxeOoDO9MyUUBRMHnVj7WgzVsxQGHtQt967sLeRKrP01TEJL4m6Yo4ZSsEIPAjGWlsjKZVMMeNk9sewwYLX9SC/PRSDFgbwBdD4zBLmaovInQ7FVxXrXyKHsC+tZqWVqWxNUuAUJVW21dSYJBQOgjYoRdVixNNu90a4kXLxWB5JPPebtdaKgOJzjKCs3YLyEnLQdQie2HhDT2cpZypCR8TttPBwtzLUxpeRFUFtrbOybjyh92bqjF4LA3I8W0fvB3U45SPGz7+g1zAvIguX1veljgSAw2IL+uaMAPNm5fEfEE63zdUiAxFA/s3U8qGfXAsbG"
    }
  }
}
